from __future__ import annotations

ACCESS_DATE = "2026-07-27"
PROJECT_TITLE = "尼泊尔海鲜AI线上销售系统"


SOURCES = [
    {
        "id": "S01",
        "title": "Nepal country data",
        "institution": "World Bank",
        "year": "2024",
        "type": "国际组织",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "人口、国内生产总值、人均国内生产总值、侨汇占比",
        "url": "https://data.worldbank.org/country/nepal?locations=NP&page=1",
        "confidence": "HIGH",
    },
    {
        "id": "S02",
        "title": "National Population and Housing Census 2021",
        "institution": "National Statistics Office, Nepal",
        "year": "2021",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "城市人口、家庭数量、城市优先级",
        "url": "https://censusnepal.cbs.gov.np/results/files/result-folder/National%20Report_English.pdf",
        "confidence": "HIGH",
    },
    {
        "id": "S03",
        "title": "Urbanization and Development in Nepal",
        "institution": "National Statistics Office, Nepal",
        "year": "2025",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "主要城市人口、增长和密度",
        "url": "https://censusnepal.cbs.gov.np/results/files/result-folder/Urbanization%20and%20Development%20in%20Nepal.pdf",
        "confidence": "HIGH",
    },
    {
        "id": "S04",
        "title": "Nepal Tourism Statistics 2024",
        "institution": "Ministry of Culture, Tourism and Civil Aviation, Nepal",
        "year": "2024",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "旅游、酒店与餐饮场景",
        "url": "https://tourism.gov.np/content/628/ne-pal-tourism-statistics-2024/",
        "confidence": "HIGH",
    },
    {
        "id": "S05",
        "title": "Nepal Tourism Insights June 2026",
        "institution": "Nepal Tourism Board",
        "year": "2026",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "旅游恢复与季节性监测",
        "url": "https://trade.ntb.gov.np/downloads-cat/nepal-tourism-statistics/",
        "confidence": "HIGH",
    },
    {
        "id": "S06",
        "title": "Agricultural Statistics Pocket Book 2023",
        "institution": "Ministry of Agriculture and Livestock Development, Nepal",
        "year": "2023",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "本地渔业与水产供给",
        "url": "https://moald.gov.np/content/40/agricultural-statistics-pocket-book-2023/",
        "confidence": "HIGH",
    },
    {
        "id": "S07",
        "title": "Status and Development Trend of Aquaculture and Fisheries in Nepal",
        "institution": "FAO AGRIS",
        "year": "2023",
        "type": "学术与国际组织",
        "official": False,
        "platform_official": False,
        "company": False,
        "use": "鱼类产量、养殖占比与人均供给",
        "url": "https://agris.fao.org/search/en/providers/122436/records/68d2a53db3b40a20d6189a7e",
        "confidence": "MEDIUM",
    },
    {
        "id": "S08",
        "title": "Unlocking Aquaculture Potential: Strategic Pathways for Its Growth in Nepal",
        "institution": "FAO AGRIS",
        "year": "2025",
        "type": "学术与国际组织",
        "official": False,
        "platform_official": False,
        "company": False,
        "use": "鱼类消费与本地养殖扩张趋势",
        "url": "https://agris.fao.org/search/en/providers/122443/records/69b97847ce5e0ae4f878edfb",
        "confidence": "MEDIUM",
    },
    {
        "id": "S09",
        "title": "Nepal HS 03 imports and source countries",
        "institution": "TrendEconomy based on UN Comtrade",
        "year": "2022",
        "type": "国际贸易数据库",
        "official": False,
        "platform_official": False,
        "company": False,
        "use": "进口额、来源国和品类结构",
        "url": "https://trendeconomy.com/data/h2/Nepal/03",
        "confidence": "MEDIUM",
    },
    {
        "id": "S10",
        "title": "Annual Foreign Trade Statistics Book 2079-80",
        "institution": "Department of Customs, Nepal",
        "year": "2022/23",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "尼泊尔外贸统计原始入口",
        "url": "https://customs.gov.np/content/43/annual-foreign-trade-statistics-book-2079-80/",
        "confidence": "HIGH",
    },
    {
        "id": "S11",
        "title": "Integrated Tariff 2082-83",
        "institution": "Department of Customs, Nepal",
        "year": "2025/26",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "按最终海关编码复核税率",
        "url": "https://customs.gov.np/content/46/integrated-tariff-rate/",
        "confidence": "HIGH",
    },
    {
        "id": "S12",
        "title": "Food Regulation 1970",
        "institution": "Department of Food Technology and Quality Control, Nepal",
        "year": "1970, current official repository",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "包装食品标签、批次、生产与到期日期、语言和误导性陈述",
        "url": "https://www.dftqc.gov.np/rules/download-%2813%29-1742819788.pdf",
        "confidence": "HIGH",
    },
    {
        "id": "S13",
        "title": "Food Act 2023 (1967)",
        "institution": "Department of Food Technology and Quality Control, Nepal",
        "year": "1967, current official repository",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "食品安全、许可、禁止误导和不合格食品",
        "url": "https://www.dftqc.gov.np/rules/download-%281%29-1742819223.pdf",
        "confidence": "HIGH",
    },
    {
        "id": "S14",
        "title": "Food import and export application through Nepal National Single Window",
        "institution": "Department of Food Technology and Quality Control, Nepal",
        "year": "2026",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "食品进出口申请入口变化",
        "url": "https://www.dftqc.gov.np/en/notice-details/136/32788974",
        "confidence": "HIGH",
    },
    {
        "id": "S15",
        "title": "DFTQC Annual Bulletin",
        "institution": "Department of Food Technology and Quality Control, Nepal",
        "year": "2025",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "食品进口许可工作量与监管入口",
        "url": "https://www.dftqc.gov.np/downloadfiles/DFTQC-Annual-Bulletin-Eng-2082-Book-for-WEB-%281%29-1779272721.pdf",
        "confidence": "HIGH",
    },
    {
        "id": "S16",
        "title": "Imports and Transit Procedure",
        "institution": "Trade and Export Promotion Centre, Nepal",
        "year": "current web page",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "进口主体、信用证、报关与基础单证",
        "url": "https://tepc.gov.np/pages/imports-transit-procedure",
        "confidence": "MEDIUM",
    },
    {
        "id": "S17",
        "title": "E-Commerce Act 2081",
        "institution": "Nepal Law Commission",
        "year": "2025",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "线上经营的本地法律复核入口",
        "url": "https://lawcommission.gov.np/content/13517/electricity-trade--e-workers--act--2081/",
        "confidence": "HIGH",
    },
    {
        "id": "S18",
        "title": "Privacy Act 2075",
        "institution": "Nepal Law Commission",
        "year": "2018",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "个人信息最小化与保护",
        "url": "https://lawcommission.gov.np/content/12261/12261-the-privacy-act-2075/",
        "confidence": "HIGH",
    },
    {
        "id": "S19",
        "title": "Electronic Transactions Act 2063",
        "institution": "Nepal Law Commission",
        "year": "2008",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "电子记录与交易",
        "url": "https://lawcommission.gov.np/content/13397/electronic--electronic--traded-international-act--2063/",
        "confidence": "HIGH",
    },
    {
        "id": "S20",
        "title": "Monthly Payment Systems Indicators: Asoj 2082",
        "institution": "Nepal Rastra Bank",
        "year": "2025",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "移动银行、电子钱包、二维码和电商支付",
        "url": "https://www.nrb.org.np/contents/uploads/2025/11/2082_06-PS-Indicator.pdf",
        "confidence": "HIGH",
    },
    {
        "id": "S21",
        "title": "Payment Systems Department and licensed providers",
        "institution": "Nepal Rastra Bank",
        "year": "2026",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "支付服务机构官方入口",
        "url": "https://www.nrb.org.np/departments/psd/",
        "confidence": "HIGH",
    },
    {
        "id": "S22",
        "title": "TikTok Shop and Showcase availability",
        "institution": "TikTok For Business",
        "year": "2026",
        "type": "平台官方",
        "official": False,
        "platform_official": True,
        "company": False,
        "use": "TikTok Shop市场清单",
        "url": "https://ads.tiktok.com/help/article/tiktok-shopping-and-showcase?redirected=1",
        "confidence": "HIGH",
    },
    {
        "id": "S23",
        "title": "Available regions for self-serve ad account creation",
        "institution": "TikTok For Business",
        "year": "2025",
        "type": "平台官方",
        "official": False,
        "platform_official": True,
        "company": False,
        "use": "TikTok广告自助开户地区",
        "url": "https://ads.tiktok.com/help/article/available-countries-and-regions-for-ad-account-creation-in-bc",
        "confidence": "HIGH",
    },
    {
        "id": "S24",
        "title": "Available location targeting options by market",
        "institution": "TikTok For Business",
        "year": "2025",
        "type": "平台官方",
        "official": False,
        "platform_official": True,
        "company": False,
        "use": "TikTok广告地区定向限制",
        "url": "https://ads.tiktok.com/help/article/placements-available-locations?lang=en",
        "confidence": "HIGH",
    },
    {
        "id": "S25",
        "title": "TikTok LIVE eligibility",
        "institution": "TikTok Help Center",
        "year": "current web page",
        "type": "平台官方",
        "official": False,
        "platform_official": True,
        "company": False,
        "use": "直播年龄、粉丝门槛与地区差异",
        "url": "https://support.tiktok.com/en/live-gifts-wallet/tiktok-live/what-is-tiktok-live",
        "confidence": "HIGH",
    },
    {
        "id": "S26",
        "title": "TikTok access restriction removed in Nepal",
        "institution": "Nepal Telecommunications Authority",
        "year": "2024",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "TikTok在尼泊尔恢复访问",
        "url": "https://nta.gov.np/content/tiktok-lie-iie-b-e-a",
        "confidence": "HIGH",
    },
    {
        "id": "S27",
        "title": "About Daraz Nepal and payment methods",
        "institution": "Daraz Nepal",
        "year": "2026",
        "type": "平台官方",
        "official": False,
        "platform_official": True,
        "company": False,
        "use": "商家入口、支付方式与平台存在性",
        "url": "https://www.daraz.com.np/about-daraz/",
        "confidence": "HIGH",
    },
    {
        "id": "S28",
        "title": "Foodmandu company and service locations",
        "institution": "Foodmandu",
        "year": "2026",
        "type": "企业官网",
        "official": False,
        "platform_official": False,
        "company": True,
        "use": "餐饮与杂货配送城市",
        "url": "https://foodmandu.com/Home/About",
        "confidence": "HIGH",
    },
    {
        "id": "S29",
        "title": "Kanomama seafood catalogue",
        "institution": "K.M Food & Processing Pvt. Ltd.",
        "year": "2026",
        "type": "企业官网",
        "official": False,
        "platform_official": False,
        "company": True,
        "use": "海鲜品类、价格与加德满都谷地配送",
        "url": "https://www.kanomama.com/",
        "confidence": "HIGH",
    },
    {
        "id": "S30",
        "title": "Valley Cold Store catalogue",
        "institution": "Valley Cold Store",
        "year": "2026",
        "type": "企业官网",
        "official": False,
        "platform_official": False,
        "company": True,
        "use": "冷冻海鲜、加工鱼品和本地零售价格",
        "url": "https://sewapoint.com/sellers/valley-cold-store-nayabazar-kathmandu/",
        "confidence": "MEDIUM",
    },
    {
        "id": "S31",
        "title": "Foodmandu frozen seafood listings",
        "institution": "Foodmandu",
        "year": "current listing",
        "type": "企业官网",
        "official": False,
        "platform_official": False,
        "company": True,
        "use": "鱼柳、虾、干货与三文鱼在售价格",
        "url": "https://foodmandu.com/Restaurant/Details/1205",
        "confidence": "MEDIUM",
    },
    {
        "id": "S32",
        "title": "Kathmandu Organics frozen products",
        "institution": "Kathmandu Organics",
        "year": "2026",
        "type": "企业官网",
        "official": False,
        "platform_official": False,
        "company": True,
        "use": "本地鳟鱼价格与配送规则",
        "url": "https://www.kathmanduorganics.com/frozen",
        "confidence": "HIGH",
    },
    {
        "id": "S33",
        "title": "Shree Kathmandu Suppliers frozen prawn",
        "institution": "Shree Kathmandu Suppliers",
        "year": "2026",
        "type": "企业官网",
        "official": False,
        "platform_official": False,
        "company": True,
        "use": "冷冻虾规格和价格",
        "url": "https://kathmandusuppliers.com.np/frozen-prawn",
        "confidence": "HIGH",
    },
    {
        "id": "S34",
        "title": "Bhat-Bhateni stores and contact",
        "institution": "Bhat-Bhateni",
        "year": "2026",
        "type": "企业官网",
        "official": False,
        "platform_official": False,
        "company": True,
        "use": "全国连锁零售入口和城市覆盖",
        "url": "https://bbsm.com.np/index.php",
        "confidence": "HIGH",
    },
    {
        "id": "S35",
        "title": "Bigmart online store",
        "institution": "Bigmart",
        "year": "2026",
        "type": "企业官网",
        "official": False,
        "platform_official": False,
        "company": True,
        "use": "加德满都线上零售与即时配送入口",
        "url": "https://bigmart.com.np/",
        "confidence": "MEDIUM",
    },
    {
        "id": "S36",
        "title": "Hotel Association Nepal",
        "institution": "Hotel Association Nepal",
        "year": "2026",
        "type": "协会官网",
        "official": False,
        "platform_official": False,
        "company": False,
        "use": "酒店名单与采购单位入口",
        "url": "https://hotelassociationnepal.org.np/index.php",
        "confidence": "HIGH",
    },
    {
        "id": "S37",
        "title": "Hotel Association Nepal membership database",
        "institution": "Hotel Association Nepal",
        "year": "2025",
        "type": "协会官网",
        "official": False,
        "platform_official": False,
        "company": False,
        "use": "酒店和度假村名单",
        "url": "https://hotelassociationnepal.org.np/storage/Membership%20database.pdf",
        "confidence": "HIGH",
    },
    {
        "id": "S38",
        "title": "Restaurant and Bar Association Nepal",
        "institution": "REBAN Nepal",
        "year": "2026",
        "type": "协会官网",
        "official": False,
        "platform_official": False,
        "company": False,
        "use": "餐饮采购单位与地区分会入口",
        "url": "https://rebannepal.com/",
        "confidence": "HIGH",
    },
    {
        "id": "S39",
        "title": "FNCCI member database",
        "institution": "Federation of Nepalese Chambers of Commerce and Industry",
        "year": "2026",
        "type": "协会官网",
        "official": False,
        "platform_official": False,
        "company": False,
        "use": "地区商会与企业名单入口",
        "url": "https://www.fncci.org/",
        "confidence": "HIGH",
    },
    {
        "id": "S40",
        "title": "Nepal Chamber of Commerce committees and contact",
        "institution": "Nepal Chamber of Commerce",
        "year": "2026",
        "type": "协会官网",
        "official": False,
        "platform_official": False,
        "company": False,
        "use": "商业网络与行业委员会入口",
        "url": "https://ncc.org.np/contact",
        "confidence": "HIGH",
    },
    {
        "id": "S41",
        "title": "Population, total - Nepal",
        "institution": "World Bank",
        "year": "2025",
        "type": "国际组织",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "最新人口",
        "url": "https://data.worldbank.org/indicator/SP.POP.TOTL?locations=NP",
        "confidence": "HIGH",
    },
    {
        "id": "S42",
        "title": "Urban population (% of total population) - Nepal",
        "institution": "World Bank",
        "year": "2025",
        "type": "国际组织",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "最新城镇化率",
        "url": "https://data.worldbank.org/indicator/SP.URB.TOTL.IN.ZS?locations=NP",
        "confidence": "HIGH",
    },
    {
        "id": "S43",
        "title": "GDP per capita (current US$) - Nepal",
        "institution": "World Bank",
        "year": "2025",
        "type": "国际组织",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "最新人均国内生产总值",
        "url": "https://data.worldbank.org/indicator/NY.GDP.PCAP.CD?locations=NP",
        "confidence": "HIGH",
    },
    {
        "id": "S44",
        "title": "Nepal Tourism Statistics 2025",
        "institution": "Ministry of Culture, Tourism and Civil Aviation, Nepal",
        "year": "2025",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "最新入境旅游量与酒店餐饮需求背景",
        "url": "https://giwmscdnone.gov.np/media/pdf_upload/Nepal%20tourism%20statistics%202025_ibddtm6.pdf",
        "confidence": "MEDIUM",
    },
    {
        "id": "S45",
        "title": "FAO Fisheries and Aquaculture Profile - Nepal",
        "institution": "Food and Agriculture Organization of the United Nations",
        "year": "2022",
        "type": "国际组织",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "人均鱼类消费与渔业概况",
        "url": "https://www.fao.org/fishery/facp/npl/en",
        "confidence": "HIGH",
    },
    {
        "id": "S46",
        "title": "Statistical Information on Nepalese Agriculture 2023/24",
        "institution": "Ministry of Agriculture and Livestock Development, Nepal",
        "year": "2023/24",
        "type": "尼泊尔官方",
        "official": True,
        "platform_official": False,
        "company": False,
        "use": "最新年度鱼类产量",
        "url": "https://giwmscdnone.gov.np/media/pdf_upload/MOALD-Statical-Book-Magre-2081-Final_wgfs8ph.pdf",
        "confidence": "HIGH",
    },
]


MARKET_FACTS = [
    ["人口", "29,618,118", "2025", "World Bank", "[KNOWN] [HIGH]", "全国潜在消费面很大，但不能直接当作海鲜可服务市场。", "S41"],
    ["城镇化率", "67%", "2025", "World Bank", "[KNOWN] [HIGH]", "城市渠道的重要性较高，但仍需按冷链可服务范围缩小。", "S42"],
    ["人均国内生产总值", "1,535.9美元", "2025", "World Bank", "[KNOWN] [HIGH]", "进口海鲜需要分层定价，不能用全国平均推断高端需求。", "S43"],
    ["侨汇收入占国内生产总值", "26.2%", "2024", "World Bank", "[KNOWN] [HIGH]", "部分城市家庭有外部收入支撑，但仍需实际价格测试。", "S01"],
    ["本地鱼类产量", "113,736吨", "2023/24", "尼泊尔农业部", "[KNOWN] [HIGH]", "本地供应主要是淡水鱼，进口海鲜应强调品类差异而不是替代所有鱼类。", "S46"],
    ["人均鱼类消费", "约3.4千克/年", "2022", "FAO", "[KNOWN] [HIGH]", "消费真实存在但频率不高，价格和教育限制明显。", "S45"],
    ["HS 03进口额", "约636万美元", "2022", "UN Comtrade再发布", "[KNOWN] [MEDIUM]", "只覆盖HS 03，不包括全部加工海鲜和本地销售，因此只能视作贸易口径下限参考。", "S09,S10"],
    ["HS 03进口额", "约1,520万美元", "2021", "UN Comtrade再发布", "[KNOWN] [MEDIUM]", "2022同比下降约58%，进口市场波动大，不宜用单一年份外推。", "S09"],
    ["HS 03来源国", "印度54%、越南42%", "2022", "UN Comtrade再发布", "[KNOWN] [MEDIUM]", "地理与既有供应关系给印度明显优势；越南在鱼柳等品类有基础。", "S09"],
    ["HS 03中国来源", "约301美元", "2022", "UN Comtrade再发布", "[KNOWN] [MEDIUM]", "当年中国份额几乎可忽略，进入需要重新建立信任和渠道。", "S09"],
    ["HS 03品类结构", "鲜冷鱼43%、鱼柳39%", "2022", "UN Comtrade再发布", "[KNOWN] [MEDIUM]", "鱼类与鱼柳占主导；虾蟹和软体类规模较小但更具差异化。", "S09"],
    ["旅游住宿供给", "1,578家、62,642床", "2024统计中的2081年数据", "尼泊尔旅游部", "[KNOWN] [HIGH]", "酒店、度假村和餐厅形成可触达的B2B场景。", "S04"],
    ["入境旅游", "1,162,365人次", "2025", "尼泊尔旅游部", "[KNOWN] [MEDIUM]", "旅游城市和酒店餐饮提供额外需求，但不能等同于海鲜采购量。", "S44"],
    ["二维码支付", "3,735.6万笔、1,217.77亿NPR", "2025年9月中至10月中", "Nepal Rastra Bank", "[KNOWN] [HIGH]", "二维码已是重要收款方式，独立商城应支持本地主流支付。", "S20"],
    ["电子钱包支付", "3,724.0万笔、469.54亿NPR", "2025年9月中至10月中", "Nepal Rastra Bank", "[KNOWN] [HIGH]", "电子钱包适合作为线上收款选项，但实际接入需本地主体。", "S20,S21"],
    ["电商卡支付", "19.62万笔、12.86亿NPR", "2025年9月中至10月中", "Nepal Rastra Bank", "[KNOWN] [HIGH]", "卡类电商支付规模明显小于钱包和二维码，货到付款仍应保留。", "S20"],
]


IMPORT_SOURCE_2022 = [
    ["印度", 54.0, 3.45],
    ["越南", 42.0, 2.67],
    ["马来西亚", 2.22, 0.141],
    ["泰国", 0.86, 0.055],
    ["其他", 0.92, 0.044],
]

IMPORT_CATEGORY_2022 = [
    ["鲜冷鱼（0302）", 43.0, 2.79],
    ["鱼柳及鱼肉（0304）", 39.0, 2.52],
    ["虾蟹等甲壳类（0306）", 4.7, 0.299],
    ["冷冻整鱼（0303）", 4.62, 0.294],
    ["干制、盐渍、熏制鱼（0305）", 4.19, 0.266],
    ["软体类（0307）", 1.46, 0.092],
    ["其他", 3.03, 0.193],
]


CITY_SCORES = [
    ["Kathmandu", 91, "第一优先", "首批启动", "人口与商业密度最高；酒店、协会、线上零售和海鲜在售证据最集中。", "MEDIUM", "S02,S03,S04,S28,S29,S34,S36,S38"],
    ["Lalitpur", 87, "第一优先", "与Kathmandu同一配送单元启动", "高密度城市、餐饮与Kanomama所在地，适合并入谷地服务圈。", "MEDIUM", "S02,S03,S29"],
    ["Bhaktapur", 81, "第一优先", "与谷地同批但限配送半径", "可共享谷地渠道；需要实际冷链时效确认。", "MEDIUM", "S02,S28,S34"],
    ["Pokhara", 75, "第二优先", "谷地复购稳定后进入", "旅游与酒店餐饮强，Foodmandu和连锁零售有入口；冷链承接需实测。", "MEDIUM", "S03,S04,S05,S28,S34,S37"],
    ["Bharatpur / Chitwan", 64, "观察与预建名单", "60天后视履约验证", "人口增长、旅游和餐饮分会存在；高端进口海鲜公开证据少。", "LOW", "S03,S28,S38"],
    ["Butwal", 59, "观察", "90天后再判断", "Foodmandu和连锁零售有覆盖线索，但海鲜需求与冷链证据不足。", "LOW", "S28,S34"],
    ["Biratnagar", 57, "观察", "不在首阶段投流", "商业城市且靠近印度供应通道，竞争与价格压力较高。", "LOW", "S03,S34"],
    ["Birgunj", 55, "观察", "优先做供应与渠道访谈", "重要口岸与商业城市，但消费端和冷链零售证据不足。", "LOW", "S03,S34"],
]


B2B_SEGMENTS = [
    ["高端酒店与度假村", 88, "第一优先", "稳定菜单、宴会和早餐/自助餐需求；HAN名录可触达。", "试样、厨师测试、交货稳定性", "S36,S37"],
    ["日料、韩餐、中餐、西餐与火锅门店", 86, "第一优先", "品类适配明确，虾、鱿鱼、鱼柳、三文鱼可直接进入菜品测试。", "厨师反馈、出成率、菜单毛利", "S38"],
    ["冷冻食品经销与批发单位", 83, "第一优先", "可放大覆盖并承接冷库与配送；同时也可能是竞争者。", "区域、冷库、最低订货量、账期", "S29,S30,S33"],
    ["高端食品店与连锁超市", 80, "第一优先", "家庭包装与即烹产品需要零售陈列和信任背书。", "上架费、损耗、退货、条码、促销", "S34,S35"],
    ["宴会与婚庆餐饮", 72, "第二优先", "单次需求大但波动和价格敏感明显。", "档期、套餐、定金、食安责任", "S38"],
    ["旅游餐饮供应单位", 69, "第二优先", "可触达酒店、度假村和旅游餐饮，但供货稳定性要求高。", "覆盖城市、冷链交接和回款", "S36,S39"],
    ["云厨房与外卖餐饮", 66, "第二优先", "可快速测试新品，但持续采购量和品牌呈现有限。", "单店销量、包装和配送", "S28"],
    ["企业食堂与团餐", 58, "暂缓", "可能有量，但价格、招采与菜单接受度不确定。", "招采周期和预算", "S39,S40"],
    ["海鲜进口与加工单位", 55, "谨慎合作", "可能拥有资质与冷链，也可能与本项目直接竞争。", "边界、区域和信息保密", "S29,S30"],
]


B2C_SEGMENTS = [
    ["加德满都谷地中高收入家庭", 88, "第一优先", "有购买力和家庭配送条件，适合500克至1千克包装。", "真实下单、复购、拒绝原因"],
    ["火锅、烧烤与家庭聚餐人群", 87, "第一优先", "场景强、内容表现好，适合组合装与简单做法。", "组合装转化、聚餐前购买"],
    ["在尼外国人与中国人", 84, "第一优先", "对进口海鲜更熟悉，可作为早期验证，不可代替本地需求。", "语言偏好、复购、产品认知"],
    ["年轻上班族与即烹需求人群", 82, "第一优先", "需要少处理、定量包装和清晰做法。", "15分钟做法内容、下单时段"],
    ["美食爱好者与主厨内容关注者", 78, "第二优先", "愿意学习新做法，适合新品内容测试。", "收藏、咨询、试购"],
    ["健身与高蛋白饮食人群", 68, "第二优先", "鱼柳和虾适配，但不能做未经证实的健康功效承诺。", "营养信息与实际购买"],
    ["节日与送礼人群", 62, "第二优先", "需要包装、价格和品牌信任，供应资料不足前不启动。", "礼盒概念与价格测试"],
    ["普通家庭", 49, "暂缓广投", "全国收入与冷链差异大，进口海鲜可能价格过高。", "低价鱼柳和小包装测试"],
]


SCENARIO_SCORES = [
    ["餐厅菜品与酒店自助餐", 91, "虾、鱿鱼、鱼柳、三文鱼", "B2B", "厨师试样和出成率"],
    ["家庭火锅", 89, "虾、鱿鱼圈、鱼片、组合装", "B2C", "组合装下单与复购"],
    ["家庭烧烤", 86, "虾、鱿鱼、鱼柳、调味即烹", "B2C", "周末与节日需求"],
    ["15分钟家庭快手菜", 84, "去壳虾、鱼柳、鱿鱼圈", "B2C", "做法清晰与少处理"],
    ["酒店宴会与婚庆餐饮", 75, "虾、鱼柳、鱿鱼", "B2B", "档期和大包装报价"],
    ["高端聚餐与礼赠", 68, "三文鱼、龙虾候选", "B2B/B2C", "价格和包装先验证"],
    ["健身高蛋白餐", 66, "鱼柳、虾", "B2C", "营养资料必须真实"],
]


PRODUCT_WEIGHTS = {
    "市场需求": 12,
    "认知基础": 8,
    "价格接受": 8,
    "竞争友好": 6,
    "供应可行": 10,
    "损耗可控": 8,
    "利润潜力": 8,
    "B2B适配": 10,
    "B2C适配": 10,
    "内容表现": 6,
    "复购潜力": 8,
    "扩张潜力": 6,
}


def product(name, category, form, pack, b2b, b2c, scores, conclusion, evidence, price="未找到可靠公开价格", source=""):
    total = round(sum(scores[k] * PRODUCT_WEIGHTS[k] / 5 for k in PRODUCT_WEIGHTS))
    return {
        "name": name,
        "category": category,
        "form": form,
        "pack": pack,
        "b2b": b2b,
        "b2c": b2c,
        "scores": scores,
        "total": total,
        "conclusion": conclusion,
        "evidence": evidence,
        "price": price,
        "source": source,
    }


BASE_HIGH = {
    "市场需求": 4,
    "认知基础": 4,
    "价格接受": 4,
    "竞争友好": 3,
    "供应可行": 4,
    "损耗可控": 4,
    "利润潜力": 4,
    "B2B适配": 4,
    "B2C适配": 4,
    "内容表现": 4,
    "复购潜力": 4,
    "扩张潜力": 4,
}


PRODUCTS = [
    product("冷冻去骨鱼柳（巴沙/龙利方向）", "鱼类", "冷冻鱼柳", "B2B 5-10千克；B2C 500克-1千克", "高", "高", {**BASE_HIGH, "市场需求": 5, "认知基础": 5, "价格接受": 5, "内容表现": 3}, "首批测试", "尼泊尔进口结构中鱼柳占比高，线上已有巴沙鱼柳与加工品。", "约900 NPR/千克", "S09,S30,S31"),
    product("裹粉鱼条/鱼块", "鱼类加工品", "冷冻即烹", "500克；餐饮大包装", "中", "高", {**BASE_HIGH, "市场需求": 4, "认知基础": 4, "价格接受": 4, "B2C适配": 5, "内容表现": 4}, "首批测试", "Valley Cold Store已有巴沙鱼条和鱼块，说明方便型产品存在。", "约690 NPR/500克", "S30"),
    product("HLSO冷冻虾 21/25", "虾类", "带头带壳冷冻", "1-1.8千克；餐饮箱", "高", "高", {**BASE_HIGH, "市场需求": 5, "认知基础": 5, "利润潜力": 4, "内容表现": 5, "复购潜力": 5}, "首批测试", "多个本地页面有同类规格，价格与场景清晰。", "约3,600-3,700 NPR/标示包装", "S29,S33"),
    product("IQF去壳去肠线虾 31/40", "虾类", "单冻净菜", "500克；1千克；餐饮箱", "高", "高", {**BASE_HIGH, "市场需求": 5, "认知基础": 5, "价格接受": 4, "供应可行": 4, "损耗可控": 5, "B2C适配": 5, "内容表现": 5, "复购潜力": 5}, "首批测试", "即烹便利性强；需要供应方提供净重、冰衣和规格证据。", "同类页面约1,250 NPR，规格未完整披露", "S30"),
    product("冷冻鱿鱼筒", "鱿鱼", "清洁鱿鱼筒", "500克-1千克；餐饮箱", "高", "高", {**BASE_HIGH, "市场需求": 4, "认知基础": 4, "价格接受": 4, "内容表现": 5, "B2B适配": 5, "复购潜力": 4}, "首批测试", "本地海鲜商已有明确在售价格，餐饮和家庭烧烤均适配。", "约1,595 NPR/标示包装", "S29"),
    product("冷冻鱿鱼圈", "鱿鱼", "切圈即烹", "500克；1千克", "高", "高", {**BASE_HIGH, "市场需求": 4, "认知基础": 4, "价格接受": 4, "B2C适配": 5, "内容表现": 5, "复购潜力": 4}, "首批测试", "本地页面已有鱿鱼圈，适合油炸、烧烤和火锅。", "约1,200 NPR，规格需复核", "S30"),
    product("海鲜火锅组合", "组合装", "冷冻多品组合", "600克-1千克", "中", "高", {**BASE_HIGH, "市场需求": 4, "认知基础": 3, "竞争友好": 5, "供应可行": 3, "B2C适配": 5, "内容表现": 5, "扩张潜力": 5}, "首批概念测试", "可把多品类转成一次消费场景，但必须解决配比、过敏原和保质期。", "未找到可靠公开价格", "S29,S30"),
    product("海鲜烧烤组合", "组合装", "串制或分格冷冻", "600克-1千克", "中", "高", {**BASE_HIGH, "市场需求": 4, "认知基础": 3, "竞争友好": 5, "供应可行": 3, "B2C适配": 5, "内容表现": 5, "扩张潜力": 5}, "首批概念测试", "周末与聚餐内容表现强，需先做口味与烹饪方式测试。", "未找到可靠公开价格", ""),
    product("蒜香/香辣即烹虾", "虾类加工品", "调味冷冻", "300-500克", "中", "高", {**BASE_HIGH, "市场需求": 4, "认知基础": 4, "竞争友好": 4, "供应可行": 3, "B2C适配": 5, "内容表现": 5}, "首批概念测试", "能降低处理门槛，但需真实配料、过敏原和本地口味验证。", "未找到可靠公开价格", ""),
    product("冷冻三文鱼柳/分切", "高端鱼类", "去皮或带皮冷冻", "150-250克分切；整侧", "高", "中", {**BASE_HIGH, "市场需求": 3, "认知基础": 4, "价格接受": 2, "利润潜力": 5, "B2B适配": 5, "B2C适配": 3, "内容表现": 5, "复购潜力": 3}, "小规模高端测试", "本地已有高价在售，适合酒店、日料和高收入家庭，不适合作为主销量品。", "约8,900 NPR/千克；150克牛排约1,450 NPR", "S29,S31"),
    product("冷冻罗非鱼柳", "鱼类", "冷冻鱼柳", "500克-1千克；餐饮箱", "高", "中", {**BASE_HIGH, "市场需求": 4, "认知基础": 4, "价格接受": 4, "竞争友好": 3, "内容表现": 3}, "候选", "与本地淡水鱼竞争明显，需要价格和出成率优势。", "未找到可靠公开价格", "S06,S07"),
    product("冷冻鲭鱼", "海鱼", "整鱼或切段", "500克-1千克；餐饮箱", "中", "中", {**BASE_HIGH, "市场需求": 3, "认知基础": 3, "价格接受": 4, "B2C适配": 3, "内容表现": 3}, "候选", "可能适合餐饮与在尼外国人，需要本地在售和口味验证。", "未找到可靠公开价格", ""),
    product("金枪鱼排", "高端鱼类", "冷冻分切", "150-250克；餐饮箱", "高", "中", {**BASE_HIGH, "市场需求": 3, "认知基础": 4, "价格接受": 2, "利润潜力": 4, "B2B适配": 5, "B2C适配": 2, "内容表现": 4}, "候选", "适合酒店西餐和日料，家庭端价格与烹饪教育成本高。", "未找到可靠公开价格", ""),
    product("冷冻墨鱼", "软体类", "整只或切片", "500克-1千克", "中", "中", {**BASE_HIGH, "市场需求": 3, "认知基础": 3, "价格接受": 3, "B2B适配": 4, "B2C适配": 3, "内容表现": 4}, "候选", "可作为鱿鱼之后的扩展品，不宜首批同时启动。", "未找到可靠公开价格", ""),
    product("冷冻章鱼", "软体类", "整只或切段", "500克-1千克；餐饮箱", "中", "低", {**BASE_HIGH, "市场需求": 2, "认知基础": 2, "价格接受": 2, "B2B适配": 4, "B2C适配": 2, "内容表现": 5, "复购潜力": 2}, "暂缓", "内容表现强但认知、价格和做法门槛高。", "未找到可靠公开价格", ""),
    product("蟹肉", "蟹类", "去壳冷冻", "250-500克；餐饮箱", "高", "中", {**BASE_HIGH, "市场需求": 3, "认知基础": 3, "价格接受": 2, "供应可行": 3, "B2B适配": 5, "B2C适配": 3}, "候选", "比整蟹更容易用于餐饮，但需真伪、添加物和净含量证明。", "未找到可靠公开价格", ""),
    product("冷冻整蟹", "蟹类", "整只冷冻", "按只或1千克", "中", "低", {**BASE_HIGH, "市场需求": 2, "认知基础": 3, "价格接受": 2, "供应可行": 2, "损耗可控": 3, "B2C适配": 2, "复购潜力": 2}, "暂缓", "价格、可食率和处理门槛高，首阶段不利于复购。", "未找到可靠公开价格", ""),
    product("龙虾", "龙虾", "整只冷冻", "按只或重量", "中", "低", {**BASE_HIGH, "市场需求": 2, "认知基础": 3, "价格接受": 1, "供应可行": 2, "利润潜力": 4, "B2B适配": 4, "B2C适配": 1, "复购潜力": 1}, "暂缓", "可做高端形象品，但不适合首批验证销量。", "未找到可靠公开价格", "S29"),
    product("扇贝柱", "贝类", "冷冻贝柱", "250-500克；餐饮箱", "中", "低", {**BASE_HIGH, "市场需求": 2, "认知基础": 2, "价格接受": 2, "供应可行": 3, "B2B适配": 4, "B2C适配": 2}, "暂缓", "餐饮可用，家庭认知和价格接受度需要验证。", "未找到可靠公开价格", ""),
    product("青口/蛤蜊", "贝类", "带壳或去壳冷冻", "500克-1千克", "中", "低", {**BASE_HIGH, "市场需求": 2, "认知基础": 2, "价格接受": 3, "供应可行": 2, "损耗可控": 3, "B2B适配": 4, "B2C适配": 2}, "暂缓", "食品安全、壳重和烹饪教育提高首阶段风险。", "未找到可靠公开价格", ""),
    product("干虾/小鱼干", "海鲜干货", "干制", "100-500克", "中", "中", {**BASE_HIGH, "市场需求": 3, "认知基础": 3, "价格接受": 3, "供应可行": 5, "损耗可控": 5, "内容表现": 2, "复购潜力": 3}, "候选", "物流友好且本地已有干虾和小鱼干，但需口味与用途定位。", "干虾约2,800 NPR/250克；小鱼干约1,100 NPR/500克", "S31"),
    product("罐装金枪鱼", "海鲜熟食", "罐装", "单罐或组合", "中", "中", {**BASE_HIGH, "市场需求": 3, "认知基础": 4, "价格接受": 3, "供应可行": 5, "损耗可控": 5, "竞争友好": 2, "内容表现": 2}, "候选但非差异化主线", "常温物流友好，但竞争和品牌替代强。", "未找到可靠公开价格", ""),
    product("海参", "高端干货", "干制或泡发冷冻", "小包装；餐饮包装", "低", "低", {**BASE_HIGH, "市场需求": 1, "认知基础": 1, "价格接受": 1, "供应可行": 3, "利润潜力": 4, "B2B适配": 2, "B2C适配": 1, "内容表现": 2, "复购潜力": 1}, "不建议首阶段进入", "市场教育和价格门槛过高，缺少公开在售证据。", "未找到可靠公开价格", ""),
    product("鲍鱼", "高端贝类", "罐装或冷冻", "单罐或小包装", "低", "低", {**BASE_HIGH, "市场需求": 1, "认知基础": 1, "价格接受": 1, "供应可行": 3, "利润潜力": 4, "B2B适配": 2, "B2C适配": 1, "内容表现": 3, "复购潜力": 1}, "不建议首阶段进入", "高价、认知低且缺少本地公开证据。", "未找到可靠公开价格", ""),
    product("冰鲜海鱼", "海鱼", "鲜冷", "按重量", "中", "中", {**BASE_HIGH, "市场需求": 3, "认知基础": 3, "价格接受": 3, "供应可行": 1, "损耗可控": 1, "B2B适配": 4, "B2C适配": 2, "复购潜力": 3}, "不建议首阶段进入", "跨境时效、温控和损耗难度高，供应资料缺失。", "未找到可靠公开价格", "S09"),
    product("活鲜海产品", "活鲜", "活体", "按只或重量", "低", "低", {**BASE_HIGH, "市场需求": 2, "认知基础": 2, "价格接受": 1, "供应可行": 1, "损耗可控": 1, "利润潜力": 2, "B2B适配": 2, "B2C适配": 1, "内容表现": 5, "复购潜力": 1}, "不建议进入", "运输、存活、检疫和售后风险不适合最小成本验证。", "未找到可靠公开价格", ""),
]


PRICE_RECORDS = [
    ["Atlantic Salmon Frozen Filet (Skin off)", "Kanomama", "冷冻三文鱼柳", "1千克", 8900, 8900, "页面显示可加入购物车", "未明确", "2026-07-27", "S29", "HIGH"],
    ["Frozen HLSO 21/25 Prawn", "Kanomama", "冷冻带头带壳虾", "页面未明确净重", 3700, None, "页面显示可加入购物车", "页面标示印度产品图标，需逐品确认", "2026-07-27", "S29", "MEDIUM"],
    ["Frozen Squid Tube Tray Pack", "Kanomama", "冷冻鱿鱼筒", "页面未明确净重", 1595, None, "页面显示可加入购物车", "未明确", "2026-07-27", "S29", "MEDIUM"],
    ["Prawn Frozen 21/25", "Shree Kathmandu Suppliers", "冷冻虾", "1.8千克块装", 3600, 2000, "页面存在加入购物车", "未明确", "2026-07-27", "S33", "HIGH"],
    ["Frozen Pangasius Fillet", "Foodmandu", "冷冻巴沙鱼柳", "1千克", 900, 900, "页面显示商品", "未明确", "2026-07-27", "S31", "MEDIUM"],
    ["Frozen Pangasius Steak", "Foodmandu", "冷冻巴沙鱼段", "500克", 490, 980, "页面显示商品", "未明确", "2026-07-27", "S31", "MEDIUM"],
    ["Medium Prawn", "Foodmandu / Nina & Hager", "冷冻虾", "500克", 1000, 2000, "页面显示商品", "未明确", "2026-07-27", "S31", "MEDIUM"],
    ["Dry Shrimp", "Foodmandu / Nina & Hager", "干虾", "250克", 2800, 11200, "页面显示商品", "未明确", "2026-07-27", "S31", "MEDIUM"],
    ["Dry Anchovy", "Foodmandu / Nina & Hager", "小鱼干", "500克", 1100, 2200, "页面显示商品", "未明确", "2026-07-27", "S31", "MEDIUM"],
    ["Salmon Steak", "Foodmandu", "三文鱼排", "150克", 1450, 9667, "页面显示商品", "未明确", "2026-07-27", "S31", "MEDIUM"],
    ["Frozen Rainbow Trout Fish", "Kathmandu Organics", "冷冻虹鳟鱼", "1千克", 1700, 1700, "页面显示可加入购物车", "尼泊尔Kaski", "2026-07-27", "S32", "HIGH"],
    ["IQF Prawn", "Valley Cold Store / SewaPoint", "单冻虾", "页面未明确净重", 1250, None, "页面显示加入按钮", "未明确", "2026-07-27", "S30", "MEDIUM"],
    ["VCS Shrimp", "Valley Cold Store / SewaPoint", "冷冻虾", "500克", 850, 1700, "页面显示加入按钮", "未明确", "2026-07-27", "S30", "MEDIUM"],
    ["Squid Rings", "Valley Cold Store / SewaPoint", "冷冻鱿鱼圈", "页面未明确净重", 1200, None, "页面显示加入按钮", "未明确", "2026-07-27", "S30", "MEDIUM"],
    ["Breaded Basa Finger", "Valley Cold Store / SewaPoint", "裹粉巴沙鱼条", "500克", 690, 1380, "页面显示加入按钮", "未明确", "2026-07-27", "S30", "MEDIUM"],
    ["Breaded Basa Nugget", "Valley Cold Store / SewaPoint", "裹粉巴沙鱼块", "500克", 690, 1380, "页面显示加入按钮", "未明确", "2026-07-27", "S30", "MEDIUM"],
]


B2B_CHANNELS = [
    ["Google Search", "已确认可用", "酒店、餐厅、经销单位、进口与冷冻食品商", "官网、目录、新闻、地图", "公开页面检索→去重→官网复核→人工联系", "高", "关键词过宽；不能抓取非公开信息", "每周有效新名单、回复率", "S36,S37,S38,S39"],
    ["Google Maps", "已确认可用", "本地餐厅、酒店、食品店、冷库", "公开地址、电话、网站、营业类别", "按城市和类别检索→官网二次确认", "高", "地图信息可能过期；联系前复核", "有效联系方式率", ""],
    ["Hotel Association Nepal", "已确认有300+成员并提供名单", "酒店与度假村", "会员名录", "按星级与城市分组→查采购入口→人工试样", "高", "协会成员不等于采购意愿", "会面数、试样数", "S36,S37"],
    ["REBAN Nepal", "已确认有地区分会和餐饮成员网络", "餐厅、酒吧、宴会餐饮", "协会与地区分会", "分会合作→餐饮名单→厨师试样", "高", "成员数量由协会自述；逐家仍需核验", "厨师测试数", "S38"],
    ["FNCCI", "已确认有地区与行业成员检索", "经销商、商会、食品企业", "成员数据库与地方商会", "地区+食品类别筛选→官网复核", "高", "类别可能不细；避免无差别触达", "合格采购单位数", "S39"],
    ["Nepal Chamber of Commerce", "已确认可用", "进口、零售、技术与供应链合作单位", "委员会与公开联系入口", "委员会引荐→一对一会谈", "中", "不把商会关系当成采购承诺", "有效引荐数", "S40"],
    ["LinkedIn", "平台存在，尼泊尔地区覆盖需逐账户验证", "酒店采购、餐饮负责人、零售管理人员", "公开职业资料与企业页", "企业优先→职位匹配→人工个性化联系", "中", "不得批量抓取或高频群发", "接受连接率、回复率", ""],
    ["Facebook", "截至2026年需现场确认账号与地区可访问性", "餐厅、酒店、食品商与社群", "企业公开主页、活动与群组", "公开页面发现→官网复核→人工沟通", "中", "尼泊尔曾出现社交平台政策波动；不可作为唯一渠道", "有效对话数", ""],
    ["Instagram", "截至2026年需现场确认账号与地区可访问性", "餐饮、主厨、进口食品店", "企业公开主页", "内容合作与私信转官网/电话", "中", "不要自动群发或冒充真人", "回复率、会面率", ""],
    ["TikTok", "内容平台已确认可访问", "餐厅、主厨、零售商的公开账号", "公开视频与企业主页", "内容发现→官网/电话→人工商务沟通", "中", "Shop不支持尼泊尔；广告能力需后台确认", "合作询问数", "S22,S23,S24,S26"],
    ["WhatsApp", "需要实际号码与本地可用性确认", "已有公开号码的采购单位", "官网公开联系方式", "仅在有业务依据后点对点沟通", "中", "不得批量添加、无差别群发或反复打扰", "回复与停止联系执行率", ""],
    ["Viber", "尼泊尔使用与注册状态有公开线索，需现场复核", "本地商户与已有联系人", "官网公开号码", "人工首触达→经同意后跟进", "中", "必须尊重拒绝与退订", "有效对话数", ""],
    ["Email", "已确认可用", "酒店、协会、连锁零售与企业采购", "官网公开邮箱", "个性化邮件→7天一次跟进→最多3次", "高", "反垃圾规则与声誉风险", "送达、回复、会面", ""],
    ["企业官网", "已确认是核心真值入口", "所有采购单位", "官网联系页、产品页、分店页", "用于身份复核和人工联系", "高", "网站可能过期；与地图/协会交叉", "官网复核率", ""],
    ["企业黄页", "可作为发现入口，质量不一", "长尾餐饮与食品商", "公开企业目录", "只做发现→官网或电话二次核验", "低", "陈旧、重复与错误较多", "二次核验通过率", ""],
    ["海关与贸易数据", "有公开统计，企业级完整名单常需付费", "进口商与品类趋势", "海关统计、UN Comtrade/WITS", "先看品类与来源→再查公开企业", "中", "免费数据粒度有限；不伪装成完整企业名单", "可验证进口单位数", "S09,S10"],
    ["酒店与餐厅预订平台", "可作为门店发现入口", "酒店、度假村、餐厅", "公开门店和菜单", "按城市/菜系筛选→官网复核", "中", "评价与排名不代表采购能力", "有效门店率", ""],
    ["招标与采购公告", "需要持续监测", "酒店集团、机构餐饮与团餐", "官网公告与政府采购入口", "关键词订阅→人工审查→正式投标", "低", "资质和周期长，首阶段不作为主线", "合格公告数", ""],
    ["本地行业社群", "需当地人员确认真实活跃度", "主厨、餐饮经营者、食品商", "协会活动与线下社群", "人工引荐和小型试样会", "中", "不可用自动账号渗透或伪装身份", "有效引荐数", "S36,S38,S39"],
]


B2C_CHANNELS = [
    ["TikTok", "已确认内容可访问；Shop不在尼泊尔市场清单", "发现、教育、评论与私信询问", "站外商城/Viber/WhatsApp/电话", "高", "内容与社群回复可半自动；发布和承诺需人工确认", "播放完成率、主页访问、有效询问、成交", "S22,S25,S26"],
    ["Facebook", "需本地实测当前稳定性", "本地社群、家庭与餐饮内容", "独立商城或消息工具", "中", "平台政策连续性风险，不作为唯一入口", "触达、有效询问、站外成交", ""],
    ["Instagram", "需本地实测当前稳定性", "美食、主厨、家庭聚餐", "独立商城或消息工具", "中", "图片和视频不得虚构产品与反馈", "收藏、私信、站外成交", ""],
    ["YouTube Shorts", "需本地实测", "食谱、处理方法、品牌教育", "独立商城或搜索", "中", "转化链较长，适合沉淀内容", "完播、搜索、落地页访问", ""],
    ["Daraz Nepal", "平台与支付方式已确认", "标准化家庭包装和常温/冷冻可履约品", "平台商品页", "中", "冷链品类、佣金和仓配必须书面确认", "上架通过、订单、退货", "S27"],
    ["Foodmandu", "已确认覆盖Kathmandu、Pokhara、Bharatpur、Butwal", "本地餐饮、杂货和冷冻品", "平台下单", "高", "供应合作、抽佣、冷链责任需商务确认", "上架、转化、履约、复购", "S28,S31"],
    ["Kanomama", "已确认海鲜垂直商城与谷地配送", "价格和品类基准；潜在合作或竞争", "自有商城", "高", "不假设可直接入驻；先做商务边界沟通", "可合作范围或竞争监测", "S29"],
    ["Kathmandu Organics", "已确认线上配送与冷冻鳟鱼", "高品质家庭食品", "自有商城", "中", "海鲜品类有限，需洽谈是否接受进口品", "合作回复、试上架", "S32"],
    ["Bigmart", "已确认线上商店与加德满都快速配送宣传", "大众零售与家庭即时购买", "平台下单", "中", "海鲜冷链能力和入驻条件待确认", "上架条件、订单", "S35"],
    ["Bhat-Bhateni", "已确认多城市连锁零售", "家庭零售和线下信任", "门店与可能的线上入口", "高", "采购、冷柜、条码、退货和促销需正式洽谈", "上架门店、周转、补货", "S34"],
    ["独立商城", "可建设", "全渠道统一成交与数据沉淀", "本地支付+货到付款", "高", "上线前必须接入真实库存、配送和售后真值", "转化、付款、履约、复购", "S17,S20,S21"],
    ["Viber / WhatsApp", "需本地实测与合规设置", "咨询、推荐、订单确认", "支付链接或货到付款", "高", "只对主动询问或已同意的联系人跟进", "响应时长、成交、退订", ""],
    ["Messenger", "需本地实测当前稳定性", "社交主页咨询", "独立商城或人工订单", "中", "平台稳定性与隐私风险", "有效询问、转化", ""],
    ["Google Search / Maps", "已确认可用", "主动搜索海鲜、冷冻品与配送的人群", "独立商城/电话/地图导航", "高", "需要本地搜索词和门店资料", "搜索点击、电话、导航、订单", ""],
    ["私域社群", "需在获得同意后建立", "复购、食谱和到货提醒", "商城链接或人工订单", "中", "禁止未经同意拉群和高频促销", "复购率、退群率", ""],
    ["达人合作", "可行性需逐人和平台规则确认", "美食、家庭、主厨与健身垂类", "专属链接或口令", "中", "不得伪造体验；必须真实试吃和披露合作", "有效询问、成交、内容成本", ""],
    ["直播", "普通直播能力需账号实测；直播带货不等于可用", "烹饪演示、答疑和新品测试", "站外下单", "中", "Shop不支持尼泊尔；价格库存必须接真值", "观看、停留、有效询问", "S22,S25"],
    ["餐厅联名", "可通过B2B合作建立", "先吃后买、主厨背书", "餐厅二维码到商城", "高", "必须是真实合作与真实菜品", "试吃、扫码、复购", "S38"],
    ["内容SEO", "可建设", "长期搜索和食谱教育", "独立商城", "中", "需要尼泊尔语与英语人工审校", "自然搜索、咨询、订单", ""],
    ["短视频广告", "TikTok/Meta地区能力需后台确认", "放大已验证素材", "落地页/商城", "待验证", "不得在未验证账号和转化追踪前设大预算", "获客成本、成交成本、退款", "S23,S24"],
]


TIKTOK_CAPABILITIES = [
    ["普通账号发布内容", "已确认平台可访问", "尼泊尔2024年解除访问限制；仍需实际注册与发布测试", "[KNOWN] [HIGH]", "可用于市场教育与有机内容", "S26"],
    ["商业账号", "部分成立", "TikTok提供商业账号，但尼泊尔本地开户、行业和功能需实测", "[INFERRED] [MEDIUM]", "先注册本地主体账号并记录可见功能", ""],
    ["TikTok Ads自助开户", "未确认可用", "官方自助开户地区清单不含Nepal", "[KNOWN] [HIGH]", "不得承诺本地自助投流；用真实后台验证或联系TikTok代表", "S23"],
    ["尼泊尔本地定向", "待验证", "官方说明定向选项取决于广告账号注册地，公开清单不能证明Nepal可被普通账号定向", "[KNOWN] [HIGH]", "真实广告后台截图是放量前闸门", "S24"],
    ["TikTok Shop", "不可按现状使用", "2026年6月官方市场清单不含Nepal", "[KNOWN] [HIGH]", "采用站外商城、Viber/WhatsApp或电话成交", "S22"],
    ["商品挂载与站内支付", "不可按现状使用", "依赖TikTok Shop或受支持的Commerce能力；Nepal不在Shop市场清单", "[INFERRED] [HIGH]", "不在方案中承诺购物袋或站内付款", "S22"],
    ["普通LIVE", "账号级待验证", "官方规定通常需18岁、约1,000粉丝且地区可能不同", "[KNOWN] [HIGH]", "达到条件后做烹饪演示；先在实际账号检查LIVE入口", "S25"],
    ["LIVE带货", "不可按现状视为可用", "直播存在不等于Shop商品和站内支付存在", "[KNOWN] [HIGH]", "直播只做演示与站外引导", "S22,S25"],
    ["达人联盟", "不可按现状视为可用", "TikTok Shop Affiliate依赖Shop市场", "[KNOWN] [HIGH]", "首阶段采用站外合同、专属链接或人工统计", "S22"],
    ["Pixel / Events API", "技术能力存在但Nepal广告实用性待验证", "只有广告账号、落地页和地区定向可用后才有价值", "[INFERRED] [MEDIUM]", "先在自有商城保留基础事件，再等待广告后台确认", "S23,S24"],
]


CONTENT_IDEAS = [
    ["1", "15分钟蒜香虾", "上班族与家庭聚餐", "从冷冻到出锅的时间线", "真实通用食材，不出现品牌、价格或库存", "评论关键词“做法”→自动发送食谱→自有页面", "完播率、食谱领取"],
    ["2", "火锅海鲜怎么选", "火锅与朋友聚餐人群", "虾、鱼片、鱿鱼的下锅顺序", "只做品类教育，不暗示已有具体组合装", "评论关键词“火锅”→组合需求调查", "有效评论、需求表完成"],
    ["3", "鱿鱼筒切圈不卷边", "家庭烹饪人群", "处理步骤与失败对比", "不使用未经确认的自有产品画面", "收藏→食谱页", "收藏率、主页访问"],
    ["4", "一包鱼柳三种做法", "年轻上班族与健身人群", "煎、烤、咖喱", "营养描述只引用确认标签，不做功效承诺", "评论“鱼柳”→做法与口味调查", "完播率、有效询问"],
    ["5", "尼泊尔香料遇上海鲜", "本地美食人群", "用jimbu、timur等本地风味做概念演示", "由当地厨师审味后再公开", "主厨合作页或调查", "当地评论质量"],
    ["6", "海鲜份量怎么估算", "家庭采购与聚餐组织者", "按人数给通用份量范围", "真实商品净重上线前不得直接套用", "人数选择→推荐品类", "推荐完成率"],
    ["7", "冷冻海鲜不是反复解冻", "重视品质与安全的人群", "解释冷冻、收货、储存和解冻", "不虚构冷链监测；只讲通用原则", "下载收货检查表", "检查表领取"],
    ["8", "厨师如何看虾的规格", "餐饮采购与美食人群", "21/25、31/40的含义", "规格解释必须与真实包装一致", "B2B试样预约", "试样询问"],
    ["9", "周末烧烤海鲜清单", "朋友聚餐人群", "采购、腌制和烤制顺序", "不发布不存在的套餐", "评论“烧烤”→需求调查", "分享率、询问"],
    ["10", "三文鱼为什么贵", "高收入家庭与酒店餐饮", "用进口、温控、分切和损耗解释价格构成", "不引用未经确认的本项目成本", "高端产品等待名单", "名单登记"],
    ["11", "海鲜过敏原一分钟", "所有家庭人群", "虾蟹、贝类与交叉接触提醒", "由食品安全负责人审核", "查看完整过敏原说明", "安全页访问"],
    ["12", "评论区答疑合集", "有明确咨询的人群", "每周整理真实问题", "不得生成虚假提问或虚假反馈", "复杂问题转人工", "解决率、转人工率"],
]


LEADS = [
    ["K.M Food & Processing / Kanomama", "Lalitpur", "海鲜供应、加工与零售", "潜在合作或竞争", "官网联系页", "kmgroup@kanomama.com", "高", "先确认可合作的品类、区域和渠道边界", "S29"],
    ["Valley Cold Store", "Kathmandu", "冷冻食品与海鲜", "经销与零售", "官网/商品页", "business@valleycoldstore.com.np", "高", "确认进口品类、冷库、批发和配送能力", "S30"],
    ["Shree Kathmandu Suppliers", "Kathmandu", "进口食品与冷冻虾", "经销与零售", "官网", "官网公开电话与邮箱", "高", "以规格和价格对标，询问批发条件", "S33"],
    ["Foodmandu", "Kathmandu / Pokhara / Bharatpur / Butwal", "餐饮与杂货配送平台", "平台合作", "官网", "info@foodmandu.com", "高", "确认冷冻品入驻、抽佣、配送责任和支付", "S28,S31"],
    ["Daraz Nepal", "全国平台", "综合电商", "平台合作", "官方商家入口", "Sell on Daraz", "中", "先书面确认冷冻食品准入和仓配模式", "S27"],
    ["Kathmandu Organics", "Kathmandu", "高品质食品线上零售", "零售合作", "官网", "官网公开电话", "中", "询问进口冷冻品的上架条件", "S32"],
    ["Bhat-Bhateni", "多城市", "连锁商超", "零售采购", "官网", "info@bbsm.com.np", "高", "联系总部采购，先做谷地门店小范围测试", "S34"],
    ["Bigmart", "Kathmandu", "连锁零售与即时配送", "零售采购", "官网", "官网联系入口", "中", "确认冷柜、入场费和即时配送温控", "S35"],
    ["Hotel Association Nepal", "全国", "酒店协会", "名单与引荐", "协会官网", "hanmembers@gmail.com", "高", "申请按城市和星级进行采购交流", "S36,S37"],
    ["REBAN Kathmandu", "Kathmandu", "餐饮协会分会", "名单与试样活动", "协会官网", "官方联系入口", "高", "组织小型厨师试样会", "S38"],
    ["REBAN Pokhara", "Pokhara", "餐饮协会分会", "第二阶段名单", "协会官网", "官方联系入口", "中", "谷地验证后再建立名单", "S38"],
    ["REBAN Sauraha / Chitwan", "Chitwan", "餐饮协会分会", "第二阶段名单", "协会官网", "官方联系入口", "中", "先确认冷链和旅游餐饮需求", "S38"],
    ["FNCCI", "全国", "商会网络", "地区与行业名单", "官网成员检索", "fncci@mos.com.np", "中", "筛选食品、酒店和零售相关组织", "S39"],
    ["Nepal Chamber of Commerce", "Kathmandu", "商会", "商业引荐", "官网", "官网联系入口", "中", "通过供应和商业委员会找采购对接", "S40"],
    ["Kathmandu Marriott Hotel", "Kathmandu", "高端酒店", "餐饮采购", "HAN会员名录", "需到酒店官网复核", "高", "查采购或餐饮负责人并发送试样说明", "S37"],
    ["Hyatt Regency Kathmandu", "Kathmandu", "高端酒店", "餐饮采购", "HAN会员名录", "需到酒店官网复核", "高", "查采购或餐饮负责人并发送试样说明", "S37"],
    ["Radisson Hotel Kathmandu", "Kathmandu", "高端酒店", "餐饮采购", "HAN会员名录", "需到酒店官网复核", "高", "查采购或餐饮负责人并发送试样说明", "S37"],
    ["The Soaltee Kathmandu", "Kathmandu", "高端酒店", "餐饮采购", "HAN会员名录", "需到酒店官网复核", "高", "查采购或餐饮负责人并发送试样说明", "S37"],
    ["Dwarika's Hotel", "Kathmandu", "精品高端酒店", "餐饮采购", "HAN会员名录", "需到酒店官网复核", "高", "强调可追溯与高端餐饮适配", "S37"],
    ["Gokarna Forest Resort", "Kathmandu Valley", "度假村", "餐饮采购", "HAN会员名录", "需到酒店官网复核", "中", "确认宴会与餐饮菜单需求", "S37"],
    ["Hotel Himalaya", "Lalitpur", "高端酒店", "餐饮采购", "HAN会员名录", "需到酒店官网复核", "高", "谷地同批试样", "S37"],
    ["Hotel Yak & Yeti", "Kathmandu", "高端酒店", "餐饮采购", "HAN会员名录", "需到酒店官网复核", "高", "谷地同批试样", "S37"],
    ["Hotel Pokhara Grande", "Pokhara", "高端酒店", "第二阶段餐饮采购", "HAN会员名录", "需到酒店官网复核", "中", "在Pokhara冷链验证后联系", "S37"],
    ["Hotel Barahi", "Pokhara", "酒店", "第二阶段餐饮采购", "HAN会员名录", "需到酒店官网复核", "中", "在Pokhara冷链验证后联系", "S37"],
    ["Tiger Palace Resort", "Lumbini / Bhairahawa area", "度假村", "后续餐饮采购", "HAN会员名录", "需到酒店官网复核", "低", "不在首阶段配送承诺内", "S37"],
]


AI_FOUNDATIONS = [
    ["供应链真值中心", "只保存已经确认的商品、价格、库存、可送区域、时效、合规文件和售后规则。所有内容、报价和答复从这里读取。", "供应方资料、库存系统、配送规则", "信息缺失时只显示“待供应方确认”", "供应链负责人"],
    ["人工确认中心", "把正式报价、样品、合同、退款、投诉、扩城、加预算和高风险内容统一送人工处理。", "各模块的升级请求", "没有批准不得自动执行", "项目负责人及对应业务负责人"],
    ["过程记录中心", "记录每一次输入、建议、批准、发送、订单、履约和异常，便于追溯。", "全部模块的过程记录", "记录不可被普通账号随意删除", "系统管理员"],
]


AI_MODULES = [
    {
        "name": "市场情报模块",
        "goal": "持续判断哪个城市、品类、渠道和消费场景更值得先做。",
        "inputs": "政府与贸易数据、平台公开页面、竞品价格、内容趋势、成交与复购结果",
        "rules": "单一低质量来源不能形成核心结论；来源冲突时降级为待验证。",
        "outputs": "城市与品类优先级、价格变化、渠道变化、每周简报",
        "trigger": "每日抓取可公开数据；每周汇总；重大政策变化即时提醒",
        "human": "进入新城市、调整主品类和修改判断权重",
        "log": "来源链接、抓取日期、变化前后、采用或驳回原因",
        "permission": "只读公开来源和授权数据",
        "fallback": "来源失效时保留上次值并标记过期，不自动填补",
        "acceptance": "重点结论有可追溯来源；变更能在周报中说明原因",
    },
    {
        "name": "产品匹配模块",
        "goal": "把真实可售商品匹配到城市、采购类型、家庭人群、场景和渠道。",
        "inputs": "供应链真值、品类评分、需求、历史询价、损耗和退货",
        "rules": "没有真实价格、库存、配送时效或最低订货量时，只给候选组合，不给正式承诺。",
        "outputs": "推荐商品组合、包装建议、替代品、风险和是否进入测试",
        "trigger": "新商品加入、库存或价格变化、新询问到达",
        "human": "正式报价、缺货替换、跨城市配送",
        "log": "采用的真值版本、推荐原因、人工修改",
        "permission": "只读真值中心；写推荐结果",
        "fallback": "真值缺失时退回补资料清单",
        "acceptance": "推荐与真实库存、价格、可送区域的一致率不低于95%",
    },
    {
        "name": "B2B获客模块",
        "goal": "把公开可验证的采购单位推进到沟通、试样、小单和复购。",
        "inputs": "官网、地图、协会名录、公开企业页、产品匹配结果",
        "rules": "名称、城市、类别和至少一处公开来源才可入库；高优先对象需两处来源；禁止无差别群发。",
        "outputs": "去重名单、优先级、联系草稿、下一步和停止联系提醒",
        "trigger": "新增名单、到期跟进、回复或拒绝",
        "human": "首次发送、电话、会面、样品、正式报价和合同",
        "log": "发现来源、评分、草稿、批准、发送、回复和停止原因",
        "permission": "只读公开商务信息；不能收集非公开个人资料",
        "fallback": "14天无回复降级；明确拒绝立即停止",
        "acceptance": "以有效沟通、试样、订单和复购为准，不以名单数量为准",
    },
    {
        "name": "内容模块",
        "goal": "用真实、易懂的内容解释品类、做法、规格、安全和消费场景。",
        "inputs": "市场趋势、真实商品资料、常见问题、真实订单反馈、授权素材",
        "rules": "没有真实商品、库存、价格、检测或合作证明时，不得写成已经存在。",
        "outputs": "选题、脚本、画面要求、字幕、封面、排期和复盘建议",
        "trigger": "每周选题；高频问题和趋势变化触发加题",
        "human": "公开发布、尼泊尔语、食品安全、价格和合作案例",
        "log": "素材来源、审校人、版本、发布时间和表现",
        "permission": "只读已批准资料；不能修改供应链真值",
        "fallback": "审校不通过时转为内部培训材料",
        "acceptance": "不出现虚假商品与承诺；有效询问和订单归因可追踪",
    },
    {
        "name": "AI咨询与销售模块",
        "goal": "回答常见问题、收集需求、推荐商品并把高风险问题转人工。",
        "inputs": "真值中心、产品匹配结果、已批准话术、订单与售后状态",
        "rules": "只回答已经确认的价格、库存、配送、做法和售后；不确定时明确说需要人工确认。",
        "outputs": "回答、推荐、订单提示、缺失信息清单和人工接管请求",
        "trigger": "网页、私信、Viber、WhatsApp或平台咨询",
        "human": "正式报价、退款、投诉、冷链异常、账期、独家和大额订单",
        "log": "问题、读取的真值版本、回答、接管与结果",
        "permission": "只读真值；可写会话和需求，不可改价格库存",
        "fallback": "无法确认时停止自动回答并转人工",
        "acceptance": "误承诺为0；常见问题准确率不低于95%",
    },
    {
        "name": "广告模块",
        "goal": "在平台允许、供应稳定和自然成交已经验证后放大有效素材。",
        "inputs": "已批准素材、可送区域、库存余量、平台规则、商城成交数据",
        "rules": "广告后置；没有可用后台、真实转化追踪、库存和配送承接时不投。",
        "outputs": "测试预算、素材组合、暂停建议、放量建议和复盘",
        "trigger": "自然成交与履约达到闸门后；每天监测",
        "human": "开户、付款、预算变化、正式上线和大幅放量",
        "log": "账户、预算、素材、审核、花费、成交与调整",
        "permission": "仅操作授权广告账户",
        "fallback": "规则变化、拒登、库存紧张或成本超限时立即暂停",
        "acceptance": "能追踪到有效询问和真实成交；不只看点击",
    },
    {
        "name": "CRM协作模块",
        "goal": "统一管理采购单位与消费者的进展、提醒、订单、售后和复购。",
        "inputs": "获客、咨询、报价、样品、订单、配送、售后与复购记录",
        "rules": "状态只能按真实动作升级；口头兴趣、寄出样品和订单不能互相替代。",
        "outputs": "待办、提醒、漏斗、沉默对象唤醒和复购计划",
        "trigger": "每次互动后实时更新；每天生成待办",
        "human": "特殊价格、投诉、退款、坏账、独家和停止合作",
        "log": "每次状态变化的时间、证据和操作者",
        "permission": "写业务状态；不能改供应链真值",
        "fallback": "资料不全时保留待验证，不自动补齐",
        "acceptance": "关键进展可追溯；90%以上活跃记录有下一步与日期",
    },
    {
        "name": "数据分析模块",
        "goal": "按城市、品类、渠道和场景给出继续、调整或暂停建议。",
        "inputs": "内容、广告、CRM、订单、配送、退款、复购与毛利",
        "rules": "以真实成交、复购、履约和可持续利润为核心；小样本不做伪精确结论。",
        "outputs": "周报、月报、未成交原因、实验建议和阶段决策",
        "trigger": "每日同步；每周复盘；30/60/90天决策",
        "human": "扩城、扩品类、加预算和停品",
        "log": "采用的数据、计算口径、建议和最终决定",
        "permission": "只读分析",
        "fallback": "缺失数据明确显示，不进行猜测补齐",
        "acceptance": "能清楚说明为什么继续、调整或暂停",
    },
]


CRM_INFO_ITEMS = [
    ["基本识别", "记录编号", "系统自动生成的唯一编号", "系统", "创建时", "否", "去重与追溯"],
    ["基本识别", "对象名称", "采购单位名称或消费者自愿提供的称呼", "公开来源或对话", "创建时", "是", "识别主体"],
    ["基本识别", "城市与区域", "实际所在城市和可配送区域", "公开来源或对话", "变化时", "是", "判断履约"],
    ["对象分类", "合作类型", "酒店、餐厅、零售、经销、家庭等", "公开来源与人工判断", "确认后", "是", "决定话术和商品"],
    ["来源", "首次发现渠道", "官网、地图、协会、TikTok、Foodmandu等", "系统", "创建时", "是", "渠道归因"],
    ["来源", "原始链接", "可以复核的公开页面", "公开来源", "变化时", "B2B必填", "证据追溯"],
    ["需求", "关注品类", "对虾、鱼柳、鱿鱼、三文鱼等的兴趣", "对话与行为", "每次互动", "否", "产品匹配"],
    ["需求", "规格与包装", "需要的规格、净重和包装形式", "对话", "确认后", "B2B重要", "报价准备"],
    ["需求", "预计用量或人数", "餐饮采购量或家庭人数", "对话", "确认后", "否", "推荐数量"],
    ["商务", "价格敏感点", "目标区间或对价格的反馈", "对话", "变化时", "否", "定价实验"],
    ["商务", "报价版本", "使用了哪一版真实价格", "真值中心", "报价时", "报价时必填", "避免价格混乱"],
    ["样品", "样品状态", "未安排、已批准、已寄出、已试用、已反馈", "人工", "变化时", "否", "试样漏斗"],
    ["订单", "订单状态", "待确认、已付款、备货、配送、完成、取消", "订单系统", "实时", "下单后必填", "履约跟踪"],
    ["订单", "实收金额", "真实收款金额与币种", "支付系统", "付款时", "付款后必填", "收入核对"],
    ["履约", "配送时效", "承诺与实际送达时间", "配送系统", "完成后", "订单后必填", "服务质量"],
    ["履约", "温控与异常", "收货温度、包装破损、延误或解冻", "配送与人工", "异常时", "异常时必填", "食安与售后"],
    ["售后", "问题分类", "质量、数量、温度、时效、价格、做法等", "人工", "发生时", "否", "改进"],
    ["结果", "未成交原因", "价格、品类、时效、信任、无需求、无回复等", "人工或AI归类", "关闭时", "关闭时必填", "复盘"],
    ["结果", "复购日期", "下一次预期采购或提醒日期", "人工或模型建议", "成交后", "否", "复购"],
    ["结果", "累计价值", "已完成订单金额和毛利", "订单与财务", "每日", "成交后必填", "价值分层"],
    ["沟通", "下一步动作", "联系、寄样、报价、回访或停止", "人工确认", "每次互动", "活跃记录必填", "工作队列"],
    ["沟通", "下一步日期", "动作应发生的日期", "人工确认", "每次互动", "活跃记录必填", "提醒"],
    ["隐私", "联系许可与停止标记", "是否同意接收跟进、是否明确拒绝", "对话", "变化时", "是", "合规"],
    ["AI建议", "建议与理由", "下一步建议及使用的证据", "数据分析模块", "每次复盘", "否", "辅助判断"],
]


SUPPLY_INFO_ITEMS = [
    ["P0", "商品", "中文、英文和尼泊尔销售名称", "上线前", "表格/系统", "静态", "没有名称无法上架和搜索"],
    ["P0", "商品", "品类、处理形态、规格、净重、毛重", "上线前", "表格/系统", "静态", "影响价格比较、推荐和物流"],
    ["P0", "商品", "包装照片、真实商品图和视频", "上线前", "文件库", "静态", "没有真实素材不得做销售内容"],
    ["P0", "食品安全", "成分、添加物、过敏原、营养信息", "上线前", "表格+证明文件", "静态", "影响标签、咨询和食安"],
    ["P0", "食品安全", "储存温度、保质期、解冻和烹饪说明", "上线前", "表格+标签样稿", "静态", "影响配送、客服和售后"],
    ["P0", "合规", "原产地、卫生、检测、进口、标签与批次证明", "上线前", "文件库", "按批次更新", "缺失会阻断正式销售"],
    ["P0", "商务", "供货价、建议零售价、B2B阶梯价和税费口径", "报价前", "受控表格/系统", "变化时", "没有真价不得正式报价"],
    ["P0", "商务", "最低订货量、交货周期、样品与赔付规则", "报价前", "表格/系统", "变化时", "影响B2B沟通和合同"],
    ["P0", "库存", "当前库存、可售、已锁定、缺货和补货日期", "销售前", "系统对接（API）", "实时或每15分钟", "避免超卖与错误承诺"],
    ["P0", "履约", "可送城市、费用、截止时间和预计送达", "销售前", "系统对接（API）", "实时或每日", "决定能否接单"],
    ["P0", "履约", "订单、退款和售后状态", "销售前", "系统对接（API）", "实时", "支持通知和人工处理"],
    ["P1", "商品", "适用场景、推荐做法与份量", "内容上线前", "表格+审核", "变化时", "影响内容和推荐"],
    ["P1", "商务", "促销支持、达人和广告预算边界", "投放前", "审批表", "按活动", "没有批准不得投放"],
    ["P1", "商务", "定制包装与礼盒能力", "相关活动前", "表格", "变化时", "影响节日与礼赠"],
    ["P1", "质量", "批次追溯、温控记录与质检记录", "规模化前", "系统/文件", "按批次", "提升信任并处理召回"],
    ["P2", "增长", "新品计划与月度供应上限", "扩品前", "表格", "每月", "用于预测和扩张"],
    ["P2", "增长", "不同城市的仓配成本和损耗", "扩城前", "财务与配送数据", "每月", "决定是否扩城"],
]


ROADMAP = [
    ["0-7天", "建立真值与闸门", "确认进口主体、可售商品、价格、库存、配送、合规文件；建立状态标签和人工确认", "供应链资料模板、阻断清单、10-20个候选商品", "P0资料至少90%齐全；未齐全商品不报价", "P0资料不足或本地合规不清", "项目负责人、供应链负责人"],
    ["8-15天", "完成市场与名单验证", "复核首城、首品类、50个高优先采购单位、10个竞品价格和3条成交路径", "优先名单、价格基准、谷地配送说明", "高优先对象至少两处公开来源", "联系方式陈旧或冷链无法承接", "市场与B2B负责人"],
    ["16-30天", "概念与B2B接触", "人工发送15-25条个性化联系；做3类无虚构内容概念；收集5-10次有效沟通", "首轮回复、拒绝原因、试样名单、内容测试结果", "有效沟通不少于5次；0误承诺", "不足5次有效沟通且两轮话术均无改善", "B2B、内容与本地人员"],
    ["31-45天", "接入真实商品与最小CRM", "接入真值中心；上线简易商品页；测试咨询、报价草稿和订单流转", "可演示的最小系统与人工确认队列", "问答准确率不低于95%；正式发送均有批准", "价格库存不能稳定更新", "系统、销售与供应链"],
    ["46-60天", "试样与小单", "推进3-5个试样或试单；测试谷地配送；记录温控、时效、退货和毛利", "真实履约记录、试单复盘、首批内容素材", "至少3个试样或试单；拒绝原因覆盖率90%", "冷链异常、负毛利或投诉无法解决", "B2B、履约与售后"],
    ["61-75天", "复购与B2C小范围验证", "追踪餐饮复购；家庭端只在可送区域测试；选择1条TikTok站外成交路径", "复购提醒、家庭订单、站外转化数据", "至少1个可复制场景；数据完整率90%", "平台或履约不支持稳定成交", "销售、内容与数据"],
    ["76-90天", "决策与扩张判断", "按城市、品类、渠道、复购、毛利和风险评估继续、调整或暂停", "90天决策报告、下一阶段预算与任务", "试单单位至少8且复购占试单不低于30%才考虑放大", "50个已验证对象、两轮实验后仍少于3个试单；或重大合规/履约问题", "项目决策组"],
]


RISKS = [
    ["冷链能力未确认", "计划上架或接单但没有温控、配送半径和时效", "解冻、变质、退款与信任受损", "首阶段只做冷冻品；先跑谷地真实配送；记录收货温度", "供应链负责人", "立即停售受影响批次并人工召回", "高"],
    ["进口与食品合规不完整", "缺少进口主体、许可、卫生、标签或批次资料", "清关、销售或平台上架受阻", "P0文件闸门；最终海关编码和税率由当地报关与监管专业人员复核", "供应链与本地合规负责人", "停止对应商品销售", "高"],
    ["AI错误承诺", "真值过期或系统自行猜测价格、库存、送达", "投诉、赔付和关系损害", "所有答复只读真值；缺失即转人工；保留日志", "系统与销售负责人", "撤回错误承诺、人工解释并复盘", "高"],
    ["TikTok能力误判", "把内容、LIVE、Ads和Shop混为一谈", "无法投流或无法站内成交", "按能力矩阵逐项验证；Shop默认不可用；用站外路径", "内容与平台负责人", "切回有机内容和自有商城", "高"],
    ["平台政策变化", "社交平台被限制、账号受限或功能调整", "流量与沟通中断", "多渠道入口、自有网站、电话与Viber/WhatsApp备份", "渠道负责人", "启用备用渠道并通知已同意联系人", "高"],
    ["自动开发过度", "高频、重复或无差别联系", "封号、投诉与声誉损害", "公开商务入口、个性化、频率上限、拒绝即停止", "B2B负责人", "停止自动任务并清理队列", "高"],
    ["虚假内容", "使用不存在的包装、检测、反馈、主厨或库存", "合规与信任风险", "授权素材与证据清单；发布前人工审校", "内容负责人", "下架、澄清并追溯来源", "高"],
    ["多语言误解", "食品、过敏原、售后或做法翻译错误", "食安与纠纷", "尼泊尔语由母语者和食品安全人员双审", "本地内容与食安负责人", "立即更正并主动通知受影响购买者", "高"],
    ["B2B与B2C价格冲突", "零售价促销低于采购单位的可接受边界", "渠道抵触与乱价", "建立价格层级、活动审批和渠道保护规则", "商务负责人", "暂停活动并逐一沟通", "中"],
    ["放量后断货", "广告增长快于库存和配送", "退款、差评与成本上升", "库存安全线、日预算上限、自动暂停建议", "供应链与广告负责人", "停投、关闭缺货商品并通知", "高"],
    ["个人信息过度收集", "采集非公开个人资料或保存不必要信息", "隐私与合规风险", "最小化收集、权限分级、停止联系标记", "系统负责人", "删除不必要数据并审计权限", "高"],
    ["价格样本失真", "页面价格过期、规格不清或缺货", "错误定价与市场判断", "保留日期、规格和可售状态；每两周复核", "市场负责人", "降级为待验证并重新采样", "中"],
    ["本地淡水鱼替代", "进口鱼柳没有明显价格或便利优势", "销量不足", "用规格、出成率、即烹和餐饮稳定供货做差异化", "产品负责人", "暂停同质整鱼，聚焦虾、鱿鱼与组合装", "中"],
    ["运输路径与成本波动", "第三国转运、汇率、燃油或边境异常", "到岸成本和交期变化", "报价有效期、成本预警、备选运输和安全库存", "供应链负责人", "暂停长期报价并重算", "高"],
]


SCALE_RULES = [
    ["扩大投入", "8个及以上试单单位；复购或补货占试单不低于30%；至少1个可复制场景；没有重大合规、履约或回款事件", "扩大同城预算、增加同类商品，不直接扩全国"],
    ["继续但调整", "3-7个试单单位，或复购占比10%-29%；某一品类、采购类型或内容明显优于中位数", "再给30天单变量实验，只改一个核心变量"],
    ["暂停获客", "联系50个已验证采购单位、完成两轮话术和组合实验后仍少于3个试单", "停止新增名单，复核商品、价格与履约"],
    ["暂停品类", "5个及以上试单后90天仍无复购，或真实毛利为负且无法通过合法方式改善", "保留历史记录，停止报价和内容"],
    ["立即停止", "重大食品安全、资质、数据造假、账号违规或持续冷链故障", "停止销售与投放，启动人工调查和召回"],
]


BUDGET_MODEL = [
    ["内容概念测试", "每个内容版本成本×版本数", "供应方资料不足时只做教育内容", "完播、收藏、有效询问", "连续6个版本均无有效询问则暂停同一角度"],
    ["自然流量运营", "每周内容制作与人工审校成本", "不包含未经确认的付费投流", "有效询问、落地页访问、订单", "4周无改善则调整账号定位"],
    ["B2B试样", "单份样品成本+包装+配送×试样数", "正式寄出需人工批准", "试用反馈、试单和复购", "试样10份少于2个试单时复盘品类或对象"],
    ["小预算广告", "日预算×测试天数×素材组数", "只有后台、地区、转化追踪、库存与履约全部通过后启用", "获客成本、成交成本、退款", "成交成本超过毛利上限或库存低于安全线立即暂停"],
    ["扩大投入", "验证期有效成交成本×目标订单数×安全系数", "不能直接套用其他国家经验", "可持续毛利、复购和履约", "复购和毛利不达闸门不扩大"],
]


CODEX_TASKS = [
    ["T01", "建立供应链真值中心", "定义商品、价格、库存、配送、合规、售后信息的唯一来源与更新频率", "14_供应链资料与数据接口清单.docx", "能用测试数据演示更新；缺失时明确阻断", "P0资料"],
    ["T02", "建立来源索引与变更监测", "保存来源、日期、口径、可信度与变化", "17_来源与引用索引.docx", "每条重点结论可回到原始链接", "公开来源"],
    ["T03", "建立公开名单采集器", "只用官方接口、授权后台、公开目录与合法导出", "06_B2B潜在合作对象数据库.docx", "去重、来源可追溯、不采集非公开个人资料", "名单规则"],
    ["T04", "建立产品评分与匹配规则", "按城市、场景、B2B/B2C、冷链和价格带输出候选", "02_尼泊尔全品类海鲜机会手册.docx", "每次结果有理由和真值版本", "T01"],
    ["T05", "建立外联草稿与人工审批队列", "AI只起草，人工批准后才发送", "07_B2B_AI获客与跟进SOP.docx", "未批准消息无法发送；拒绝后停止", "T03,T04"],
    ["T06", "建立CRM状态机", "固化待验证、已联系、沟通、试样、订单、复购、暂停与淘汰", "13_CRM信息项与销售漏斗设计.docx", "每次升级有证据和时间", "T05"],
    ["T07", "建立咨询与转人工系统", "只读真值回答常见问题，复杂问题进入人工", "11_AI销售系统总体架构.docx", "误承诺为0；接管记录完整", "T01,T06"],
    ["T08", "建立内容生产工作流", "趋势、选题、脚本、素材、字幕、审校、发布和复盘", "09_TikTok专项运营与AI内容方案.docx", "无真实商品时不会生成库存、价格或反馈", "T01,T02"],
    ["T09", "建立TikTok站外成交页", "内容→落地页→支付/货到付款→订单→供应链", "09_TikTok专项运营与AI内容方案.docx", "全链路事件可追踪；Shop关闭时仍可用", "T01,T07"],
    ["T10", "接入本地支付", "评估电子钱包、二维码、卡和货到付款", "08_B2C线上销售全渠道方案.docx", "本地主体、退款和对账可验证", "本地支付协议"],
    ["T11", "接入订单与库存同步", "可售库存、锁定、缺货、订单和退款实时同步", "14_供应链资料与数据接口清单.docx", "不会超卖；异常有回退", "供应方系统"],
    ["T12", "建立广告闸门", "后台可用、地区定向、库存、配送、素材与预算全部通过后才允许投放", "16_风险_停止投入_扩大投入标准.docx", "任何一项不通过即阻断", "实际广告后台"],
    ["T13", "建立周报与阶段决策", "按城市、品类、渠道、成交、复购、履约和毛利输出建议", "15_30_60_90天执行计划.docx", "输出继续、调整或暂停理由", "T06,T11"],
    ["T14", "建立权限与审计", "分开读取、编辑、批准、发送与退款权限", "12_AI_Agent功能与数据流设计.docx", "高风险动作有双重确认和不可删日志", "组织账号"],
    ["T15", "建立测试与回退", "为价格过期、缺货、平台不可用、支付失败和冷链异常做演练", "18_后续Codex5.5执行任务包.docx", "每类异常有可执行回退", "各系统"],
]
