"""Synthetic-only ingestion contracts and staging pipeline."""

from modules.ingestion.approval import (
    ApprovalAction,
    ApprovalAuditEvent,
    ApprovalBoundaryError,
    ApprovalDecision,
    ApprovalRequest,
    ApprovalRequestState,
    ApprovedSyntheticTruthVersion,
    HumanDecisionCommand,
    RefreshConsumer,
    ReviewRequestCommand,
    RiskLevel,
    SyntheticApprovalPublisher,
    SyntheticTruthStatus,
    TruthFactsChanged,
)
from modules.ingestion.contracts import (
    FailureStage,
    ExtractionResultRecord,
    FieldLocator,
    IngestionBoundaryError,
    IngestionFailureRecord,
    IngestionJobRecord,
    IngestionOutcome,
    IngestionOutcomeState,
    IngestionWorkflowState,
    PrivateStorageLocator,
    RegisterSourceCommand,
    SourceDisposition,
    SourceFileRecord,
    SourceKind,
    StagingCandidateRecord,
    SyntheticFieldDescriptor,
)
from modules.ingestion.pipeline import IngestionPipeline
from modules.ingestion.ports import ExtractorPort
from modules.ingestion.store import InMemoryIngestionStore

__all__ = [
    "ApprovalAction",
    "ApprovalAuditEvent",
    "ApprovalBoundaryError",
    "ApprovalDecision",
    "ApprovalRequest",
    "ApprovalRequestState",
    "ApprovedSyntheticTruthVersion",
    "FailureStage",
    "ExtractionResultRecord",
    "ExtractorPort",
    "FieldLocator",
    "HumanDecisionCommand",
    "InMemoryIngestionStore",
    "IngestionBoundaryError",
    "IngestionFailureRecord",
    "IngestionJobRecord",
    "IngestionOutcome",
    "IngestionOutcomeState",
    "IngestionPipeline",
    "IngestionWorkflowState",
    "PrivateStorageLocator",
    "RegisterSourceCommand",
    "RefreshConsumer",
    "ReviewRequestCommand",
    "RiskLevel",
    "SourceDisposition",
    "SourceFileRecord",
    "SourceKind",
    "StagingCandidateRecord",
    "SyntheticApprovalPublisher",
    "SyntheticFieldDescriptor",
    "SyntheticTruthStatus",
    "TruthFactsChanged",
]
