"""P05-02 synthetic CRM ownership contracts."""

from modules.crm.domain import (
    Contact,
    CrmBoundaryError,
    CrmExport,
    CrmExportService,
    CrmRecordSet,
    CrmRepository,
    CrmStage,
    DncRecord,
    DncRegistry,
    Interaction,
    InteractionKind,
    LeadReviewDecision,
    Opportunity,
    Organization,
    RetentionIntent,
    SyntheticLeadCandidate,
)
from modules.crm.outreach import (
    OutreachBoundaryError,
    OutreachDraft,
    OutreachDraftCommand,
    OutreachDraftReceipt,
    OutreachDraftService,
    OutreachDraftState,
    OutreachFactLock,
    OutreachFactRef,
    OutreachFactStatus,
    OutreachManualHandoff,
    OutreachRisk,
    OutreachZeroSendProof,
)

__all__ = [
    "Contact",
    "CrmBoundaryError",
    "CrmExport",
    "CrmExportService",
    "CrmRecordSet",
    "CrmRepository",
    "CrmStage",
    "DncRecord",
    "DncRegistry",
    "Interaction",
    "InteractionKind",
    "LeadReviewDecision",
    "OutreachBoundaryError",
    "OutreachDraft",
    "OutreachDraftCommand",
    "OutreachDraftReceipt",
    "OutreachDraftService",
    "OutreachDraftState",
    "OutreachFactLock",
    "OutreachFactRef",
    "OutreachFactStatus",
    "OutreachManualHandoff",
    "OutreachRisk",
    "OutreachZeroSendProof",
    "Opportunity",
    "Organization",
    "RetentionIntent",
    "SyntheticLeadCandidate",
]
