"""Fail-closed settings and feature-flag contracts."""

from core.security.feature_flags import (
    FailClosedFeatureFlags,
    FeatureFlagName,
    FeatureFlagPort,
)
from core.security.settings import (
    ConfigStatus,
    ControlPlaneSettings,
    default_settings,
    fail_closed_settings,
)
from core.security.isolation import (
    AuditPolicyResult,
    InMemoryIsolationAuditLog,
    IsolationAction,
    IsolationAuditEvent,
    IsolationPolicy,
    IsolationTarget,
    PolicyDeniedError,
    PolicyEvaluation,
    disabled_feature_flag_snapshot,
)
from core.security.action_policy import (
    ActionApprovalAuditEvent,
    ActionApprovalDecision,
    ActionApprovalRequest,
    ActionApprovalService,
    ActionName,
    ActionPolicy,
    ActionPolicyError,
    ActorRole,
    ApprovalAction,
    ApprovalState,
    Environment,
    PolicyActor,
    PolicyDecision,
    PolicyPhase,
    PolicyRequest,
)

__all__ = [
    "ConfigStatus",
    "ControlPlaneSettings",
    "FailClosedFeatureFlags",
    "FeatureFlagName",
    "FeatureFlagPort",
    "ActionApprovalAuditEvent",
    "ActionApprovalDecision",
    "ActionApprovalRequest",
    "ActionApprovalService",
    "ActionName",
    "ActionPolicy",
    "ActionPolicyError",
    "ActorRole",
    "ApprovalAction",
    "ApprovalState",
    "AuditPolicyResult",
    "Environment",
    "InMemoryIsolationAuditLog",
    "IsolationAction",
    "IsolationAuditEvent",
    "IsolationPolicy",
    "IsolationTarget",
    "PolicyActor",
    "PolicyDeniedError",
    "PolicyDecision",
    "PolicyPhase",
    "PolicyRequest",
    "PolicyEvaluation",
    "default_settings",
    "fail_closed_settings",
    "disabled_feature_flag_snapshot",
]
